<?php
/**
 * Atwix
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 * @category    Atwix
 * @package     Atwix_UniversalAnalytics
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Interactiv4_GAConversionTrack_Block_Ua
 */
?>
<?php $helper = Mage::helper('rf_subscribe/metrics') ?>
<?php if ($helper->isBot()) : ?>
	<?php $helper->setBotCookie() ?>
<?php else : ?>
    <?php $accountId = Mage::helper('i4gaconversiontrack')->getAccount() ?>
    <?php if ($accountId) : ?>
        <!-- BEGIN GOOGLE GLOBAL SITE TAG CODEs 
        <script async src="//www.googletagmanager.com/gtag/js?id=<?= $accountId ?>"></script>
	-->

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NFH3JTT"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

        <script>
        //<![CDATA[
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments) }
            gtag('js', new Date());
            gtag('config', '<?= $accountId ?>', '<?= $this->getAccountParams() ?>');

            <?php if ($product = Mage::registry('current_product')) : ?>
                gtag('event', 'view_item', {
                    'items': [
                        {
                            'id'    : '<?= $product->getId() ?>',
                            'name'  : '<?= $product->getName() ?>',
                            'price' : '<?= $product->getPrice() ?>'
                        }
                    ]
                });
            <?php endif ?>

            <?php // echo $this->_getOrdersTrackingCode() ?>
        //]]>
        </script>
        <!-- BEGIN GOOGLE GLOBAL SITE TAG CODEs -->
    <?php endif ?>

	<script type="text/javascript">var _kmq = _kmq || [];
	    var _kmk = _kmk || '208767706627e7fe8616e051213653655c97e966';
        function _kms(u){
            setTimeout(function() {
                var d = document, f = d.getElementsByTagName('script')[0],
                s = d.createElement('script');
                s.type = 'text/javascript'; s.async = true; s.src = u;
                f.parentNode.insertBefore(s, f);
            }, 1);
        }
        _kms('//i.kissmetrics.com/i.js');
        _kms('//scripts.kissmetrics.com/' + _kmk + '.2.js');
	</script>
<?php endif ?>
